<a href="https://colab.research.google.com/github/amannnn-10/Movie-recommendation-system/blob/main/Movie_Recommendation_system.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [121]:
import numpy as np
import pandas as pd

In [122]:
movies = pd.read_csv('tmdb_5000_movies.csv')
credits = pd.read_csv('tmdb_5000_credits.csv')

In [123]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [124]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [125]:
credits.head(1)['crew'].values

array(['[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "depart

In [126]:
movies.merge(credits,on='title').shape

(4809, 23)

In [127]:
movies.shape

(4803, 20)

In [128]:
credits.shape

(4803, 4)

In [129]:
movies=movies.merge(credits,on='title')

In [130]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [131]:
movies['original_language'].value_counts()

en    4510
fr      70
es      32
zh      27
de      27
hi      19
ja      16
it      14
ko      12
cn      12
ru      11
pt       9
da       7
sv       5
nl       4
fa       4
th       3
he       3
ta       2
cs       2
ro       2
id       2
ar       2
vi       1
sl       1
ps       1
no       1
ky       1
hu       1
pl       1
af       1
nb       1
tr       1
is       1
xx       1
te       1
el       1
Name: original_language, dtype: int64

In [132]:
#Columns to keep
# genres
#id
#keywords
#title 
#overview
#cast
#crew

movies[['movie_id','genres','overview','title','keywords','cast','crew']]

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...
4804,9367,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",El Mariachi just wants to play his guitar and ...,El Mariachi,"[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4805,72766,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",A newlywed couple's honeymoon is upended by th...,Newlyweds,[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4806,231617,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","""Signed, Sealed, Delivered"" introduces a dedic...","Signed, Sealed, Delivered","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4807,126186,[],When ambitious New York attorney Sam is sent t...,Shanghai Calling,[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4808,25975,"[{""id"": 99, ""name"": ""Documentary""}]",Ever since the second grade when he first saw ...,My Date with Drew,"[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [133]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 901.7+ KB

In [134]:
movies=movies[['movie_id','genres','overview','title','keywords','cast','crew']]

In [135]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [138]:
movies.isnull().sum()

movie_id    0
genres      0
overview    0
title       0
keywords    0
cast        0
crew        0
dtype: int64

In [137]:
movies.dropna(inplace=True)

In [139]:
movies.duplicated().sum()

0

In [140]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [141]:
 #[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]
 #[''Action','Adventure','Fantasy','Scifi']

In [142]:
import ast

In [143]:
def convert (object):
  L = []
  for i in ast.literal_eval(object):
    L.append(i['name'])
    return L

In [144]:
movies['genres']=movies['genres'].apply(convert)

In [145]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"In the 22nd century, a paraplegic Marine is di...",Avatar,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,[Adventure],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,[Action],A cryptic message from Bondâ€™s past sends him o...,Spectre,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,[Action],Following the death of District Attorney Harve...,The Dark Knight Rises,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,[Action],"John Carter is a war-weary, former military ca...",John Carter,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [146]:
movies['keywords']=movies['keywords'].apply(convert)

In [147]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"In the 22nd century, a paraplegic Marine is di...",Avatar,[culture clash],"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,[Adventure],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,[ocean],"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,[Action],A cryptic message from Bondâ€™s past sends him o...,Spectre,[spy],"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,[Action],Following the death of District Attorney Harve...,The Dark Knight Rises,[dc comics],"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,[Action],"John Carter is a war-weary, former military ca...",John Carter,[based on novel],"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [148]:
import ast

In [149]:
import ast

def convert3(object):
    L = []
    counter = 0
    for i in ast.literal_eval(object):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

In [150]:
movies['cast'] = movies['cast'].apply(convert3)

In [151]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"In the 22nd century, a paraplegic Marine is di...",Avatar,[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,[Adventure],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,[Action],A cryptic message from Bondâ€™s past sends him o...,Spectre,[spy],"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,[Action],Following the death of District Attorney Harve...,The Dark Knight Rises,[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,[Action],"John Carter is a war-weary, former military ca...",John Carter,[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [152]:
movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [153]:
import ast

In [154]:
import ast

def fetch_director(object):
    L = []
    if object is None or not object:
        return L
    for i in ast.literal_eval(object):
        if isinstance(i, dict) and i.get('job') == 'Director':
            L.append(i.get('name'))
            break
    return L

In [155]:
movies['crew'].apply(fetch_director)

0           [James Cameron]
1          [Gore Verbinski]
2              [Sam Mendes]
3       [Christopher Nolan]
4          [Andrew Stanton]
               ...
4804     [Robert Rodriguez]
4805         [Edward Burns]
4806          [Scott Smith]
4807          [Daniel Hsia]
4808     [Brian Herzlinger]
Name: crew, Length: 4806, dtype: object

In [156]:
movies['crew']=movies['crew'].apply(fetch_director)

In [157]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"In the 22nd century, a paraplegic Marine is di...",Avatar,[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,[Adventure],"Captain Barbossa, long believed to be dead, ha...",Pirates of the Caribbean: At World's End,[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,[Action],A cryptic message from Bondâ€™s past sends him o...,Spectre,[spy],"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,[Action],Following the death of District Attorney Harve...,The Dark Knight Rises,[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,[Action],"John Carter is a war-weary, former military ca...",John Carter,[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [158]:
movies['overview'].apply(lambda x:x.split())

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bondâ€™s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...
4804    [El, Mariachi, just, wants, to, play, his, gui...
4805    [A, newlywed, couple's, honeymoon, is, upended...
4806    ["Signed,, Sealed,, Delivered", introduces, a,...
4807    [When, ambitious, New, York, attorney, Sam, is...
4808    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4806, dtype: object

In [159]:
movies['overview']=movies['overview'].apply(lambda x:x.split())

In [160]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [161]:
movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

0            [Action]
1         [Adventure]
2            [Action]
3            [Action]
4            [Action]
            ...
4804         [Action]
4805         [Comedy]
4806         [Comedy]
4807               []
4808    [Documentary]
Name: genres, Length: 4806, dtype: object

In [162]:
movies['genres']=movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

In [163]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[culture clash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dc comics],"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[based on novel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [164]:
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

In [165]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[cultureclash],"[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dccomics],"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[basedonnovel],"[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [166]:
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

In [167]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[cultureclash],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[James Cameron]
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[Gore Verbinski]
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[Sam Mendes]
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dccomics],"[ChristianBale, MichaelCaine, GaryOldman]",[Christopher Nolan]
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[basedonnovel],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[Andrew Stanton]

In [168]:
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x] if x is not None else [])

In [169]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[cultureclash],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dccomics],"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[basedonnovel],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [170]:
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [171]:
movies.head()

,movie_id,genres,overview,title,keywords,cast,crew,tags
0,19995,[Action],"[In, the, 22nd, century,, a, paraplegic, Marin...",Avatar,[cultureclash],"[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,[Adventure],"[Captain, Barbossa,, long, believed, to, be, d...",Pirates of the Caribbean: At World's End,[ocean],"[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,[Action],"[A, cryptic, message, from, Bondâ€™s, past, send...",Spectre,[spy],"[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,[Action],"[Following, the, death, of, District, Attorney...",The Dark Knight Rises,[dccomics],"[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,[Action],"[John, Carter, is, a, war-weary,, former, mili...",John Carter,[basedonnovel],"[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [172]:
new_df = movies[['movie_id','title','tags']]

In [173]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [174]:
new_df['tags'].apply(lambda x:" ".join(x))

0       In the 22nd century, a paraplegic Marine is di...
1       Captain Barbossa, long believed to be dead, ha...
2       A cryptic message from Bondâ€™s past sends him o...
3       Following the death of District Attorney Harve...
4       John Carter is a war-weary, former military ca...
                              ...
4804    El Mariachi just wants to play his guitar and ...
4805    A newlywed couple's honeymoon is upended by th...
4806    "Signed, Sealed, Delivered" introduces a dedic...
4807    When ambitious New York attorney Sam is sent t...
4808    Ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [175]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

<ipython-input-175-53a061086f2e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [176]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."

In [177]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action cultureclash SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [178]:
new_df ['tags'].apply(lambda x:x.lower())

0       in the 22nd century, a paraplegic marine is di...
1       captain barbossa, long believed to be dead, ha...
2       a cryptic message from bondâ€™s past sends him o...
3       following the death of district attorney harve...
4       john carter is a war-weary, former military ca...
                              ...
4804    el mariachi just wants to play his guitar and ...
4805    a newlywed couple's honeymoon is upended by th...
4806    "signed, sealed, delivered" introduces a dedic...
4807    when ambitious new york attorney sam is sent t...
4808    ever since the second grade when he first saw ...
Name: tags, Length: 4806, dtype: object

In [179]:
#Now converting it into lower case
new_df ['tags']=new_df ['tags'].apply(lambda x:x.lower())

<ipython-input-179-04ed1325a3db>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df ['tags']=new_df ['tags'].apply(lambda x:x.lower())

In [180]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

In [181]:
!pip install nltk

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: nltk in /usr/local/lib/python3.10/dist-packages (3.8.1)
Requirement already satisfied: click in /usr/local/lib/python3.10/dist-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in /usr/local/lib/python3.10/dist-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.10/dist-packages (from nltk) (2022.10.31)
Requirement already satisfied: tqdm in /usr/local/lib/python3.10/dist-packages (from nltk) (4.65.0)

In [198]:
import nltk

In [199]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

In [203]:
def stem(text):
    y = []
  
    for i in text.split():
        if isinstance(i, str):  # Check if i is a string
            y.append(ps.stem(i.lower()))
        else:
            y.append(str(i))

    return " ".join(y)

In [204]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-204-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [205]:
new_df['tags'][0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action cultureclash samworthington zoesaldana sigourneyweav jamescameron'

In [206]:
new_df['tags'][1300]

'a pair of age box rival are coax out of retir to fight one final bout -- 30 year after their last match. comedi fathersonrelationship robertdeniro sylvesterstallon alanarkin peterseg'

In [207]:
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a parapleg marin is dispa..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believ to be dead, ha c..."
2,206647,Spectre,a cryptic messag from bondâ€™ past send him on a...
3,49026,The Dark Knight Rises,follow the death of district attorney harvey d...
4,49529,John Carter,"john carter is a war-weary, former militari ca..."

In [208]:
from sklearn.feature_extraction.text import CountVectorizer

In [209]:
# Create the CountVectorizer object
cv = CountVectorizer(max_features=5000, stop_words='english')

In [210]:
# Fit and transform the text data
vectors = cv.fit_transform(new_df['tags']).toarray()

In [211]:
!pip install --upgrade scikit-learn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.22.4)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.1.0)

In [215]:
from sklearn.metrics.pairwise import cosine_similarity

In [216]:
cosine_similarity(vectors)

array([[1.        , 0.        , 0.04499213, ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.03370999, 0.        ,
        0.03580574],
       [0.04499213, 0.        , 1.        , ..., 0.02956562, 0.        ,
        0.        ],
       ...,
       [0.        , 0.03370999, 0.02956562, ..., 1.        , 0.04494666,
        0.04828045],
       [0.        , 0.        , 0.        , ..., 0.04494666, 1.        ,
        0.09548198],
       [0.        , 0.03580574, 0.        , ..., 0.04828045, 0.09548198,
        1.        ]])

In [217]:
cosine_similarity(vectors).shape

(4806, 4806)

In [218]:
similarity=cosine_similarity(vectors)

In [219]:
similarity[0]

array([1.        , 0.        , 0.04499213, ..., 0.        , 0.        ,
       0.        ])

In [220]:
enumerate(similarity[0])

In [221]:
list(enumerate(similarity[0]))

[(0, 0.9999999999999996),
 (1, 0.0),
 (2, 0.04499212706658475),
 (3, 0.11946953821789978),
 (4, 0.07647191129018724),
 (5, 0.03823595564509362),
 (6, 0.06424925662032355),
 (7, 0.11803342130469503),
 (8, 0.0),
 (9, 0.07647191129018724),
 (10, 0.0),
 (11, 0.03539961627023943),
 (12, 0.0),
 (13, 0.03582871819500093),
 (14, 0.0837707816583391),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 0.027420424855354085),
 (19, 0.03673591791853225),
 (20, 0.042238860309551166),
 (21, 0.041204282171516456),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.02782074420373286),
 (26, 0.042601432284230495),
 (27, 0.09280323373346189),
 (28, 0.059234887775909226),
 (29, 0.064888568452305),
 (30, 0.03673591791853225),
 (31, 0.11128297681493143),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.07987230638308718),
 (37, 0.0),
 (38, 0.06024752331287778),
 (39, 0.0),
 (40, 0.04335549847620599),
 (41, 0.03673591791853225),
 (42, 0.0),
 (43, 0.11470786693528086),
 (44, 0.05564148840746572),
 (45, 0.09037128496931668),
 (46, 0.047836487323493986),
 (47, 0.09280323373346189),
 (48, 0.06243905410544626),
 (49, 0.0),
 (50, 0.0),
 (51, 0.029867384554474945),
 (52, 0.08240856434303291),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.05407380704358751),
 (57, 0.0),
 (58, 0.09832102880166932),
 (59, 0.054453277011733005),
 (60, 0.0),
 (61, 0.05407380704358751),
 (62, 0.07254762501100116),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.07987230638308718),
 (68, 0.10526315789473682),
 (69, 0.0),
 (70, 0.03993615319154359),
 (71, 0.0),
 (72, 0.09782319760890368),
 (73, 0.0),
 (74, 0.11314714296070713),
 (75, 0.04188539082916955),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.02518164825829395),
 (81, 0.0),
 (82, 0.0),
 (83, 0.06765100914917382),
 (84, 0.0),
 (85, 0.04919189679432818),
 (86, 0.0),
 (87, 0.042601432284230495),
 (88, 0.0),
 (89, 0.021300716142115247),
 (90, 0.0),
 (91, 0.12166606584807188),
 (92, 0.0),
 (93, 0.07543142864047142),
 (94, 0.12725695259515554),
 (95, 0.0),
 (96, 0.04188539082916955),
 (97, 0.03458572319330373),
 (98, 0.0),
 (99, 0.03934447376823168),
 (100, 0.0),
 (101, 0.04188539082916955),
 (102, 0.09037128496931668),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.03771571432023571),
 (107, 0.03419927840283847),
 (108, 0.0),
 (109, 0.0),
 (110, 0.03823595564509362),
 (111, 0.042601432284230495),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.028676966733820218),
 (119, 0.03934447376823168),
 (120, 0.0),
 (121, 0.0),
 (122, 0.05263157894736841),
 (123, 0.0),
 (124, 0.0),
 (125, 0.019252140716412975),
 (126, 0.08111071056538126),
 (127, 0.1433848336691011),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.03934447376823168),
 (132, 0.03382550457458691),
 (133, 0.0),
 (134, 0.11846977555181845),
 (135, 0.0),
 (136, 0.0),
 (137, 0.02158161683875751),
 (138, 0.10526315789473682),
 (139, 0.11470786693528086),
 (140, 0.06622661785325219),
 (141, 0.0),
 (142, 0.0),
 (143, 0.032773676267223106),
 (144, 0.05263157894736841),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.09782319760890368),
 (149, 0.10039117221153818),
 (150, 0.11128297681493143),
 (151, 0.06917144638660747),
 (152, 0.05006261743217588),
 (153, 0.05973476910894989),
 (154, 0.047836487323493986),
 (155, 0.030386856273138196),
 (156, 0.03721614637823934),
 (157, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 0.027420424855354085),
 (161, 0.0),
 (162, 0.047836487323493986),
 (163, 0.04055535528269063),
 (164, 0.07987230638308718),
 (165, 0.0),
 (166, 0.042601432284230495),
 (167, 0.04588314677411235),
 (168, 0.041204282171516456),
 (169, 0.03539961627023943),
 (170, 0.06839855680567694),
 (171, 0.0),
 (172, 0.11128297681493143),
 (173, 0.0),
 (174, 0.04335549847620599),
 (175, 0.03993615319154359),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.03934447376823168),
 (181, 0.04415107856883479),
 (182, 0.03673591791853225),
 (183, 0.0),
 (184, 0.03993615319154359),
 (185, 0.0),
 (186, 0.0),
 (187, 0.07987230638308718),
 (188, 0.031512674583162724),
 (189, 0.06131393394849658),
 (190, 0.0),
 (191, 0.0),
 (192, 0.07647191129018724),
 (193, 0.022388683141982252),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.03823595564509362),
 (200, 0.06917144638660747),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.08111071056538126),
 (205, 0.0),
 (206, 0.057353933467640436),
 (207, 0.04335549847620599),
 (208, 0.0),
 (209, 0.10526315789473682),
 (210, 0.041204282171516456),
 (211, 0.0),
 (212, 0.03582871819500093),
 (213, 0.03627381250550058),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.06692744814102546),
 (218, 0.059234887775909226),
 (219, 0.0899842541331695),
 (220, 0.0),
 (221, 0.0),
 (222, 0.028676966733820218),
 (223, 0.03823595564509362),
 (224, 0.031512674583162724),
 (225, 0.03673591791853225),
 (226, 0.0),
 (227, 0.04415107856883479),
 (228, 0.06839855680567694),
 (229, 0.0519524333466131),
 (230, 0.05647824947249049),
 (231, 0.0),
 (232, 0.047836487323493986),
 (233, 0.0),
 (234, 0.03993615319154359),
 (235, 0.04055535528269063),
 (236, 0.09567297464698797),
 (237, 0.05006261743217588),
 (238, 0.0),
 (239, 0.028027592733560522),
 (240, 0.04335549847620599),
 (241, 0.0),
 (242, 0.04188539082916955),
 (243, 0.03771571432023571),
 (244, 0.1025978352085154),
 (245, 0.0),
 (246, 0.032124628310161774),
 (247, 0.0),
 (248, 0.07543142864047142),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (252, 0.03419927840283847),
 (253, 0.064888568452305),
 (254, 0.04188539082916955),
 (255, 0.0),
 (256, 0.06131393394849658),
 (257, 0.04499212706658475),
 (258, 0.0),
 (259, 0.05407380704358751),
 (260, 0.0),
 (261, 0.04588314677411235),
 (262, 0.07543142864047142),
 (263, 0.05407380704358751),
 (264, 0.0),
 (265, 0.0),
 (266, 0.04588314677411235),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.03823595564509362),
 (271, 0.03934447376823168),
 (272, 0.0),
 (273, 0.03382550457458691),
 (274, 0.05735393346764043),
 (275, 0.1538967528127731),
 (276, 0.0),
 (277, 0.028027592733560522),
 (278, 0.0),
 (279, 0.07079923254047886),
 (280, 0.0),
 (281, 0.07079923254047886),
 (282, 0.06997114285413195),
 (283, 0.042601432284230495),
 (284, 0.0),
 (285, 0.029135827337403247),
 (286, 0.13109470506889243),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0512989176042577),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.04415107856883479),
 (295, 0.04499212706658475),
 (296, 0.03673591791853225),
 (297, 0.0),
 (298, 0.0),
 (299, 0.06765100914917382),
 (300, 0.08671099695241198),
 (301, 0.057353933467640436),
 (302, 0.03419927840283847),
 (303, 0.042601432284230495),
 (304, 0.05619514869490164),
 (305, 0.0),
 (306, 0.0),
 (307, 0.09131087488821056),
 (308, 0.05407380704358751),
 (309, 0.0),
 (310, 0.0),
 (311, 0.1573778950729267),
 (312, 0.07443229275647868),
 (313, 0.03993615319154359),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.1025978352085154),
 (320, 0.04891159880445184),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.06554735253444621),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.03539961627023943),
 (338, 0.0),
 (339, 0.03934447376823168),
 (340, 0.03934447376823168),
 (341, 0.04415107856883479),
 (342, 0.10968169942141634),
 (343, 0.029373674772302332),
 (344, 0.04188539082916955),
 (345, 0.03346372407051273),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.03673591791853225),
 (351, 0.0),
 (352, 0.0),
 (353, 0.061868822488974594),
 (354, 0.041204282171516456),
 (355, 0.061868822488974594),
 (356, 0.05263157894736841),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.03771571432023571),
 (361, 0.03993615319154359),
 (362, 0.047836487323493986),
 (363, 0.032773676267223106),
 (364, 0.0),
 (365, 0.04335549847620599),
 (366, 0.04055535528269063),
 (367, 0.0),
 (368, 0.0),
 (369, 0.08240856434303291),
 (370, 0.04588314677411235),
 (371, 0.0),
 (372, 0.07165743639000186),
 (373, 0.05564148840746572),
 (374, 0.0),
 (375, 0.031512674583162724),
 (376, 0.0),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0),
 (380, 0.047836487323493986),
 (381, 0.0),
 (382, 0.0),
 (383, 0.03627381250550058),
 (384, 0.0),
 (385, 0.0),
 (386, 0.03823595564509362),
 (387, 0.03823595564509362),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.04415107856883479),
 (393, 0.0),
 (394, 0.04055535528269063),
 (395, 0.0),
 (396, 0.07987230638308718),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.04335549847620599),
 (403, 0.0324442842261525),
 (404, 0.04891159880445184),
 (405, 0.09567297464698797),
 (406, 0.0324442842261525),
 (407, 0.0),
 (408, 0.05407380704358751),
 (409, 0.0),
 (410, 0.0),
 (411, 0.03934447376823168),
 (412, 0.06997114285413195),
 (413, 0.04188539082916955),
 (414, 0.0),
 (415, 0.029373674772302332),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.03458572319330373),
 (421, 0.041204282171516456),
 (422, 0.05263157894736841),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.057807331301607985),
 (429, 0.0),
 (430, 0.04499212706658475),
 (431, 0.0),
 (432, 0.0734718358370645),
 (433, 0.05006261743217588),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.041204282171516456),
 (438, 0.0734718358370645),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0468292905790847),
 (442, 0.03934447376823168),
 (443, 0.0),
 (444, 0.0),
 (445, 0.07443229275647868),
 (446, 0.03993615319154359),
 (447, 0.06917144638660747),
 (448, 0.0),
 (449, 0.1404878717372541),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.04055535528269063),
 (454, 0.04335549847620599),
 (455, 0.13006649542861798),
 (456, 0.03419927840283847),
 (457, 0.04188539082916955),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.04055535528269063),
 (462, 0.02341464528954235),
 (463, 0.0),
 (464, 0.0),
 (465, 0.0),
 (466, 0.0),
 (467, 0.09280323373346189),
 (468, 0.04335549847620599),
 (469, 0.029373674772302332),
 (470, 0.0),
 (471, 0.030934411244487297),
 (472, 0.041204282171516456),
 (473, 0.03721614637823934),
 (474, 0.0),
 (475, 0.06765100914917382),
 (476, 0.09782319760890368),
 (477, 0.0),
 (478, 0.06554735253444621),
 (479, 0.0),
 (480, 0.07443229275647868),
 (481, 0.0),
 (482, 0.0),
 (483, 0.09782319760890368),
 (484, 0.0),
 (485, 0.0),
 (486, 0.023789303403490322),
 (487, 0.05263157894736841),
 (488, 0.02549063709672908),
 (489, 0.0),
 (490, 0.0),
 (491, 0.06554735253444621),
 (492, 0.03627381250550058),
 (493, 0.02282771872205264),
 (494, 0.0),
 (495, 0.10012523486435176),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.03993615319154359),
 (501, 0.0),
 (502, 0.03498557142706597),
 (503, 0.04335549847620599),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (507, 0.13834289277321493),
 (508, 0.04055535528269063),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.042601432284230495),
 (513, 0.11633501014942217),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.031512674583162724),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.03673591791853225),
 (523, 0.03673591791853225),
 (524, 0.0),
 (525, 0.041204282171516456),
 (526, 0.05564148840746572),
 (527, 0.0),
 (528, 0.0),
 (529, 0.23677853202210838),
 (530, 0.04055535528269063),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.06622661785325219),
 (535, 0.07443229275647868),
 (536, 0.03934447376823168),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0512989176042577),
 (540, 0.07543142864047142),
 (541, 0.03065696697424829),
 (542, 0.028239124736245246),
 (543, 0.0),
 (544, 0.04499212706658475),
 (545, 0.0),
 (546, 0.0),
 (547, 0.057353933467640436),
 (548, 0.0),
 (549, 0.03539961627023943),
 (550, 0.0),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.0),
 (556, 0.042601432284230495),
 (557, 0.06997114285413195),
 (558, 0.0),
 (559, 0.0),
 (560, 0.026144349280800103),
 (561, 0.0),
 (562, 0.04891159880445184),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (568, 0.15018785229652765),
 (569, 0.03771571432023571),
 (570, 0.11846977555181845),
 (571, 0.0),
 (572, 0.03498557142706597),
 (573, 0.03627381250550058),
 (574, 0.03419927840283847),
 (575, 0.0),
 (576, 0.04188539082916955),
 (577, 0.0468292905790847),
 (578, 0.0),
 (579, 0.06622661785325219),
 (580, 0.03498557142706597),
 (581, 0.04499212706658475),
 (582, 0.12166606584807188),
 (583, 0.0),
 (584, 0.06131393394849658),
 (585, 0.04055535528269063),
 (586, 0.03539961627023943),
 (587, 0.03771571432023571),
 (588, 0.03673591791853225),
 (589, 0.07165743639000186),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.05407380704358751),
 (595, 0.06692744814102546),
 (596, 0.10495671428119792),
 (597, 0.0),
 (598, 0.0),
 (599, 0.020855975806414705),
 (600, 0.06554735253444621),
 (601, 0.025334729596906993),
 (602, 0.11020775375559674),
 (603, 0.08111071056538126),
 (604, 0.0),
 (605, 0.03673591791853225),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.03582871819500093),
 (610, 0.06335829046432676),
 (611, 0.0),
 (612, 0.0),
 (613, 0.05407380704358751),
 (614, 0.04588314677411235),
 (615, 0.09782319760890368),
 (616, 0.05006261743217588),
 (617, 0.0468292905790847),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.05564148840746572),
 (622, 0.031512674583162724),
 (623, 0.0),
 (624, 0.059234887775909226),
 (625, 0.0),
 (626, 0.05407380704358751),
 (627, 0.06131393394849658),
 (628, 0.0),
 (629, 0.03721614637823934),
 (630, 0.0),
 (631, 0.04188539082916955),
 (632, 0.03934447376823168),
 (633, 0.03382550457458691),
 (634, 0.0917662935482247),
 (635, 0.07543142864047142),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.05973476910894989),
 (641, 0.0),
 (642, 0.0),
 (643, 0.03771571432023571),
 (644, 0.04188539082916955),
 (645, 0.04335549847620599),
 (646, 0.042601432284230495),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.03934447376823168),
 (651, 0.0),
 (652, 0.0324442842261525),
 (653, 0.059234887775909226),
 (654, 0.03498557142706597),
 (655, 0.03627381250550058),
 (656, 0.0),
 (657, 0.026669037353133248),
 (658, 0.03823595564509362),
 (659, 0.0),
 (660, 0.05006261743217588),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.04415107856883479),
 (665, 0.03721614637823934),
 (666, 0.0),
 (667, 0.0),
 (668, 0.14673479641335552),
 (669, 0.0),
 (670, 0.0),
 (671, 0.03673591791853225),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.057353933467640436),
 (678, 0.12780429685269148),
 (679, 0.0),
 (680, 0.03993615319154359),
 (681, 0.0),
 (682, 0.0),
 (683, 0.03823595564509362),
 (684, 0.0),
 (685, 0.05006261743217588),
 (686, 0.05263157894736841),
 (687, 0.04188539082916955),
 (688, 0.0),
 (689, 0.0),
 (690, 0.0),
 (691, 0.0468292905790847),
 (692, 0.03823595564509362),
 (693, 0.057353933467640436),
 (694, 0.03823595564509362),
 (695, 0.0),
 (696, 0.03673591791853225),
 (697, 0.0),
 (698, 0.033113308926626096),
 (699, 0.059234887775909226),
 (700, 0.047836487323493986),
 (701, 0.0),
 (702, 0.042601432284230495),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.04588314677411235),
 (709, 0.029135827337403247),
 (710, 0.02845551966122361),
 (711, 0.04055535528269063),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.047836487323493986),
 (716, 0.0),
 (717, 0.0),
 (718, 0.03498557142706597),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.041204282171516456),
 (725, 0.0),
 (726, 0.0),
 (727, 0.04565543744410528),
 (728, 0.0),
 (729, 0.0734718358370645),
 (730, 0.022496063533292376),
 (731, 0.03934447376823168),
 (732, 0.03458572319330373),
 (733, 0.031512674583162724),
 (734, 0.03458572319330373),
 (735, 0.03419927840283847),
 (736, 0.0468292905790847),
 (737, 0.05263157894736841),
 (738, 0.0),
 (739, 0.059234887775909226),
 (740, 0.03771571432023571),
 (741, 0.08830215713766958),
 (742, 0.0),
 (743, 0.0),
 (744, 0.0),
 (745, 0.12565617248750865),
 (746, 0.0),
 (747, 0.028676966733820218),
 (748, 0.0),
 (749, 0.0),
 (750, 0.03673591791853225),
 (751, 0.0),
 (752, 0.06839855680567694),
 (753, 0.04335549847620599),
 (754, 0.0),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.03419927840283847),
 (759, 0.0),
 (760, 0.0),
 (761, 0.04499212706658475),
 (762, 0.11128297681493143),
 (763, 0.0),
 (764, 0.0),
 (765, 0.041204282171516456),
 (766, 0.05263157894736841),
 (767, 0.03993615319154359),
 (768, 0.030934411244487297),
 (769, 0.0),
 (770, 0.0),
 (771, 0.0),
 (772, 0.0),
 (773, 0.057353933467640436),
 (774, 0.06362847629757777),
 (775, 0.04188539082916955),
 (776, 0.0),
 (777, 0.1037571695799112),
 (778, 0.13764944032233706),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.06997114285413195),
 (783, 0.0),
 (784, 0.0),
 (785, 0.028027592733560522),
 (786, 0.07868894753646336),
 (787, 0.08671099695241198),
 (788, 0.03771571432023571),
 (789, 0.0),
 (790, 0.08000711205939974),
 (791, 0.0),
 (792, 0.0),
 (793, 0.0),
 (794, 0.08671099695241198),
 (795, 0.0),
 (796, 0.0),
 (797, 0.059234887775909226),
 (798, 0.0),
 (799, 0.028676966733820218),
 (800, 0.0),
 (801, 0.0),
 (802, 0.0),
 (803, 0.0),
 (804, 0.07443229275647868),
 (805, 0.04415107856883479),
 (806, 0.0),
 (807, 0.0917662935482247),
 (808, 0.0),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.0),
 (813, 0.04055535528269063),
 (814, 0.03458572319330373),
 (815, 0.0),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0468292905790847),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (823, 0.0837707816583391),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.03771571432023571),
 (828, 0.04499212706658475),
 (829, 0.0),
 (830, 0.04499212706658475),
 (831, 0.03498557142706597),
 (832, 0.0),
 (833, 0.03823595564509362),
 (834, 0.042601432284230495),
 (835, 0.03877833671647406),
 (836, 0.032773676267223106),
 (837, 0.0),
 (838, 0.06131393394849658),
 (839, 0.0),
 (840, 0.047836487323493986),
 (841, 0.0),
 (842, 0.0),
 (843, 0.08520286456846099),
 (844, 0.0),
 (845, 0.0),
 (846, 0.031814238148788886),
 (847, 0.06997114285413195),
 (848, 0.0),
 (849, 0.0),
 (850, 0.06362847629757777),
 (851, 0.03673591791853225),
 (852, 0.0),
 (853, 0.0),
 (854, 0.08671099695241198),
 (855, 0.0),
 (856, 0.03627381250550058),
 (857, 0.0),
 (858, 0.0),
 (859, 0.08520286456846099),
 (860, 0.04919189679432818),
 (861, 0.0),
 (862, 0.04891159880445184),
 (863, 0.0917662935482247),
 (864, 0.0),
 (865, 0.0),
 (866, 0.11846977555181845),
 (867, 0.0),
 (868, 0.0),
 (869, 0.03721614637823934),
 (870, 0.07868894753646336),
 (871, 0.07868894753646336),
 (872, 0.0),
 (873, 0.03419927840283847),
 (874, 0.0),
 (875, 0.04415107856883479),
 (876, 0.0),
 (877, 0.0),
 (878, 0.05263157894736841),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.03771571432023571),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (887, 0.0),
 (888, 0.03582871819500093),
 (889, 0.08111071056538127),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.02649064714130087),
 (894, 0.08671099695241198),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.03823595564509362),
 (899, 0.04891159880445184),
 (900, 0.0),
 (901, 0.03934447376823168),
 (902, 0.0),
 (903, 0.0),
 (904, 0.0),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (909, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.06362847629757777),
 (915, 0.0),
 (916, 0.047836487323493986),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0512989176042577),
 (921, 0.0),
 (922, 0.04499212706658475),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.04188539082916955),
 (930, 0.07254762501100116),
 (931, 0.0),
 (932, 0.07987230638308718),
 (933, 0.03121952705272313),
 (934, 0.0),
 (935, 0.06131393394849658),
 (936, 0.0),
 (937, 0.0837707816583391),
 (938, 0.03823595564509362),
 (939, 0.05298129428260174),
 (940, 0.0),
 (941, 0.057353933467640436),
 (942, 0.15294382258037448),
 (943, 0.0),
 (944, 0.0),
 (945, 0.059234887775909226),
 (946, 0.03539961627023943),
 (947, 0.0),
 (948, 0.0),
 (949, 0.0),
 (950, 0.0324442842261525),
 (951, 0.10526315789473682),
 (952, 0.047836487323493986),
 (953, 0.0),
 (954, 0.0),
 (955, 0.042601432284230495),
 (956, 0.0),

In [222]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])

[(0, 0.9999999999999996),
 (529, 0.23677853202210838),
 (4405, 0.22941573387056174),
 (3608, 0.22710998958306752),
 (3083, 0.1908854288927333),
 (2786, 0.18394180184548975),
 (2148, 0.17660431427533915),
 (2999, 0.1720618004029213),
 (2409, 0.15974461276617435),
 (311, 0.1573778950729267),
 (275, 0.1538967528127731),
 (942, 0.15294382258037448),
 (568, 0.15018785229652765),
 (972, 0.15018785229652765),
 (1216, 0.14933692277237473),
 (668, 0.14673479641335552),
 (3720, 0.14509525002200233),
 (3999, 0.14350946197048195),
 (127, 0.1433848336691011),
 (4048, 0.14119562368122623),
 (449, 0.1404878717372541),
 (973, 0.1404878717372541),
 (1616, 0.1404878717372541),
 (507, 0.13834289277321493),
 (778, 0.13764944032233706),
 (3622, 0.13497638119975425),
 (2674, 0.13245323570650439),
 (3527, 0.13245323570650439),
 (4010, 0.13245323570650439),
 (286, 0.13109470506889243),
 (455, 0.13006649542861798),
 (2060, 0.13006649542861798),
 (1659, 0.1284985132406471),
 (678, 0.12780429685269148),
 (1519, 0.12780429685269148),
 (94, 0.12725695259515554),
 (3978, 0.12725695259515554),
 (745, 0.12565617248750865),
 (1204, 0.12565617248750865),
 (2204, 0.12565617248750865),
 (1149, 0.12361284651454937),
 (1344, 0.12361284651454937),
 (1438, 0.12262786789699316),
 (2584, 0.12262786789699316),
 (3462, 0.12262786789699316),
 (91, 0.12166606584807188),
 (582, 0.12166606584807188),
 (1161, 0.12166606584807188),
 (3675, 0.12166606584807188),
 (3, 0.11946953821789978),
 (134, 0.11846977555181845),
 (570, 0.11846977555181845),
 (866, 0.11846977555181845),
 (1534, 0.11846977555181845),
 (2971, 0.11846977555181845),
 (3621, 0.11846977555181845),
 (4011, 0.11846977555181845),
 (7, 0.11803342130469503),
 (2372, 0.11803342130469503),
 (1775, 0.11749469908920933),
 (513, 0.11633501014942217),
 (3879, 0.11633501014942217),
 (995, 0.11470786693528087),
 (1254, 0.11470786693528087),
 (2645, 0.11470786693528087),
 (43, 0.11470786693528086),
 (139, 0.11470786693528086),
 (4538, 0.11470786693528086),
 (74, 0.11314714296070713),
 (1121, 0.11164843913471803),
 (1455, 0.11164843913471803),
 (3443, 0.11164843913471803),
 (31, 0.11128297681493143),
 (150, 0.11128297681493143),
 (172, 0.11128297681493143),
 (762, 0.11128297681493143),
 (1089, 0.11128297681493143),
 (1109, 0.11128297681493143),
 (1348, 0.11128297681493143),
 (3055, 0.11128297681493143),
 (3716, 0.11128297681493143),
 (4192, 0.11128297681493143),
 (602, 0.11020775375559674),
 (4268, 0.11020775375559674),
 (4483, 0.11020775375559674),
 (342, 0.10968169942141634),
 (2404, 0.10882143751650175),
 (2772, 0.10814761408717502),
 (3103, 0.10814761408717502),
 (3839, 0.10814761408717502),
 (4018, 0.10814761408717502),
 (4351, 0.10814761408717502),
 (4472, 0.10814761408717502),
 (3225, 0.10619884881071828),
 (68, 0.10526315789473682),
 (138, 0.10526315789473682),
 (209, 0.10526315789473682),
 (951, 0.10526315789473682),
 (2593, 0.10526315789473682),
 (596, 0.10495671428119792),
 (1056, 0.10495671428119792),
 (2109, 0.10495671428119792),
 (777, 0.1037571695799112),
 (3588, 0.1037571695799112),
 (244, 0.1025978352085154),
 (319, 0.1025978352085154),
 (1492, 0.1025978352085154),
 (2218, 0.1025978352085154),
 (3195, 0.1025978352085154),
 (1099, 0.10147651372376074),
 (149, 0.10039117221153818),
 (1462, 0.10039117221153818),
 (495, 0.10012523486435176),
 (1166, 0.10012523486435176),
 (1274, 0.10012523486435176),
 (1726, 0.10012523486435176),
 (2250, 0.10012523486435176),
 (3152, 0.10012523486435176),
 (1191, 0.0993399267798783),
 (3310, 0.0993399267798783),
 (58, 0.09832102880166932),
 (72, 0.09782319760890368),
 (148, 0.09782319760890368),
 (476, 0.09782319760890368),
 (483, 0.09782319760890368),
 (615, 0.09782319760890368),
 (1707, 0.09782319760890368),
 (2355, 0.09782319760890368),
 (2865, 0.09782319760890368),
 (3770, 0.09782319760890368),
 (3982, 0.09782319760890368),
 (3881, 0.09733285267845751),
 (1479, 0.09637388493048532),
 (236, 0.09567297464698797),
 (405, 0.09567297464698797),
 (1259, 0.09567297464698797),
 (1469, 0.09567297464698797),
 (2075, 0.09567297464698797),
 (2622, 0.09567297464698797),
 (2741, 0.09567297464698797),
 (2549, 0.09544271444636665),
 (1004, 0.0936585811581694),
 (1667, 0.0936585811581694),
 (2053, 0.0936585811581694),
 (2817, 0.0936585811581694),
 (2824, 0.0936585811581694),
 (4355, 0.0936585811581694),
 (27, 0.09280323373346189),
 (47, 0.09280323373346189),
 (467, 0.09280323373346189),
 (3093, 0.09280323373346189),
 (2256, 0.09197090092274487),
 (634, 0.0917662935482247),
 (807, 0.0917662935482247),
 (863, 0.0917662935482247),
 (1275, 0.0917662935482247),
 (1486, 0.0917662935482247),
 (2228, 0.0917662935482247),
 (4087, 0.0917662935482247),
 (307, 0.09131087488821056),
 (2760, 0.09116056881941459),
 (45, 0.09037128496931668),
 (102, 0.09037128496931668),
 (1783, 0.09037128496931668),
 (219, 0.0899842541331695),
 (2556, 0.0899842541331695),
 (3164, 0.0899842541331695),
 (4652, 0.0899842541331695),
 (1497, 0.08885233166386383),
 (1741, 0.08885233166386383),
 (741, 0.08830215713766958),
 (1178, 0.08830215713766958),
 (2216, 0.08830215713766958),
 (2224, 0.08830215713766958),
 (2235, 0.08830215713766958),
 (2295, 0.08830215713766958),
 (2652, 0.08830215713766958),
 (3322, 0.08830215713766958),
 (3340, 0.08830215713766958),
 (3754, 0.08830215713766958),
 (1898, 0.08812102431690699),
 (2570, 0.08740748201220974),
 (3331, 0.08710071126186843),
 (300, 0.08671099695241198),
 (787, 0.08671099695241198),
 (794, 0.08671099695241198),
 (854, 0.08671099695241198),
 (894, 0.08671099695241198),
 (2397, 0.08671099695241198),
 (3109, 0.08671099695241198),
 (3634, 0.08671099695241198),
 (4112, 0.08671099695241198),
 (1356, 0.08603090020146065),
 (1965, 0.08603090020146065),
 (843, 0.08520286456846099),
 (859, 0.08520286456846099),
 (1006, 0.08520286456846099),
 (1854, 0.08520286456846099),
 (1920, 0.08520286456846099),
 (2181, 0.08520286456846099),
 (4046, 0.08520286456846099),
 (1491, 0.08479449518438636),
 (14, 0.0837707816583391),
 (823, 0.0837707816583391),
 (937, 0.0837707816583391),
 (1015, 0.0837707816583391),
 (1141, 0.0837707816583391),
 (2243, 0.0837707816583391),
 (3386, 0.0837707816583391),
 (3838, 0.0837707816583391),
 (52, 0.08240856434303291),
 (369, 0.08240856434303291),
 (1440, 0.08240856434303291),
 (1808, 0.08240856434303291),
 (1823, 0.08240856434303291),
 (1982, 0.08240856434303291),
 (1997, 0.08240856434303291),
 (3320, 0.08240856434303291),
 (3926, 0.08240856434303291),
 (2190, 0.08167991551759951),
 (889, 0.08111071056538127),
 (2115, 0.08111071056538127),
 (126, 0.08111071056538126),
 (204, 0.08111071056538126),
 (603, 0.08111071056538126),
 (1447, 0.08111071056538126),
 (1449, 0.08111071056538126),
 (1530, 0.08111071056538126),
 (2022, 0.08111071056538126),
 (2128, 0.08111071056538126),
 (3628, 0.08111071056538126),
 (3888, 0.08111071056538126),
 (3919, 0.08111071056538126),
 (4624, 0.08111071056538126),
 (4636, 0.08111071056538126),
 (4754, 0.08111071056538126),
 (4330, 0.0805532420311582),
 (3810, 0.08017658293783156),
 (790, 0.08000711205939974),
 (36, 0.07987230638308718),
 (67, 0.07987230638308718),
 (164, 0.07987230638308718),
 (187, 0.07987230638308718),
 (396, 0.07987230638308718),
 (932, 0.07987230638308718),
 (2219, 0.07987230638308718),
 (2450, 0.07987230638308718),
 (2813, 0.07987230638308718),
 (3084, 0.07987230638308718),
 (786, 0.07868894753646336),
 (870, 0.07868894753646336),
 (871, 0.07868894753646336),
 (1237, 0.07868894753646336),
 (1454, 0.07868894753646336),
 (2302, 0.07868894753646336),
 (2768, 0.07868894753646336),
 (4657, 0.07868894753646336),
 (2049, 0.0781166566864507),
 (1293, 0.07755667343294811),
 (4626, 0.07755667343294811),
 (4, 0.07647191129018724),
 (9, 0.07647191129018724),
 (192, 0.07647191129018724),
 (1276, 0.07647191129018724),
 (1320, 0.07647191129018724),
 (1771, 0.07647191129018724),
 (2232, 0.07647191129018724),
 (2709, 0.07647191129018724),
 (3025, 0.07647191129018724),
 (3102, 0.07647191129018724),
 (3755, 0.07647191129018724),
 (93, 0.07543142864047142),
 (248, 0.07543142864047142),
 (262, 0.07543142864047142),
 (540, 0.07543142864047142),
 (635, 0.07543142864047142),
 (988, 0.07543142864047142),
 (1248, 0.07543142864047142),
 (1401, 0.07543142864047142),
 (1847, 0.07543142864047142),
 (2008, 0.07543142864047142),
 (2333, 0.07543142864047142),
 (3299, 0.07543142864047142),
 (3874, 0.07543142864047142),
 (2519, 0.07465089026901592),
 (312, 0.07443229275647868),
 (445, 0.07443229275647868),
 (480, 0.07443229275647868),
 (535, 0.07443229275647868),
 (804, 0.07443229275647868),
 (1030, 0.07443229275647868),
 (1070, 0.07443229275647868),
 (1523, 0.07443229275647868),
 (1614, 0.07443229275647868),
 (4265, 0.07443229275647868),
 (432, 0.0734718358370645),
 (438, 0.0734718358370645),
 (729, 0.0734718358370645),
 (1278, 0.0734718358370645),
 (2013, 0.0734718358370645),
 (2984, 0.0734718358370645),
 (3673, 0.0734718358370645),
 (62, 0.07254762501100116),
 (930, 0.07254762501100116),
 (1634, 0.07254762501100116),
 (1970, 0.07254762501100116),
 (2820, 0.07254762501100116),
 (2880, 0.07254762501100116),
 (3393, 0.07254762501100116),
 (3485, 0.07254762501100116),
 (3620, 0.07254762501100116),
 (3728, 0.07254762501100116),
 (3795, 0.07254762501100116),
 (3854, 0.07254762501100116),
 (4281, 0.07254762501100116),
 (4502, 0.07254762501100116),
 (4606, 0.07254762501100116),
 (4757, 0.07254762501100116),
 (4019, 0.07214791053658226),
 (372, 0.07165743639000186),
 (589, 0.07165743639000186),
 (1305, 0.07165743639000186),
 (1537, 0.07165743639000186),
 (1906, 0.07165743639000186),
 (2305, 0.07165743639000186),
 (2520, 0.07165743639000186),
 (279, 0.07079923254047886),
 (281, 0.07079923254047886),
 (2740, 0.07079923254047886),
 (3389, 0.07079923254047886),
 (3423, 0.07079923254047886),
 (282, 0.06997114285413195),
 (412, 0.06997114285413195),
 (557, 0.06997114285413195),
 (782, 0.06997114285413195),
 (847, 0.06997114285413195),
 (1087, 0.06997114285413195),
 (1531, 0.06997114285413195),
 (2130, 0.06997114285413195),
 (2448, 0.06997114285413195),
 (3012, 0.06997114285413195),
 (3162, 0.06997114285413195),
 (151, 0.06917144638660747),
 (200, 0.06917144638660747),
 (447, 0.06917144638660747),
 (1201, 0.06917144638660747),
 (1272, 0.06917144638660747),
 (2100, 0.06917144638660747),
 (2331, 0.06917144638660747),
 (2432, 0.06917144638660747),
 (2445, 0.06917144638660747),
 (2634, 0.06917144638660747),
 (3078, 0.06917144638660747),
 (3146, 0.06917144638660747),
 (3497, 0.06917144638660747),
 (3553, 0.06917144638660747),
 (3595, 0.06917144638660747),
 (3611, 0.06917144638660747),
 (3748, 0.06917144638660747),
 (3886, 0.06917144638660747),
 (170, 0.06839855680567694),
 (228, 0.06839855680567694),
 (752, 0.06839855680567694),
 (1067, 0.06839855680567694),
 (1538, 0.06839855680567694),
 (2488, 0.06839855680567694),
 (83, 0.06765100914917382),
 (299, 0.06765100914917382),
 (475, 0.06765100914917382),
 (1639, 0.06765100914917382),
 (1677, 0.06765100914917382),
 (3020, 0.06765100914917382),
 (217, 0.06692744814102546),
 (595, 0.06692744814102546),
 (997, 0.06692744814102546),
 (1127, 0.06692744814102546),
 (1281, 0.06692744814102546),
 (1457, 0.06692744814102546),
 (2363, 0.06692744814102546),
 (2650, 0.06692744814102546),
 (3478, 0.06692744814102546),
 (2294, 0.06653536832815835),
 (140, 0.06622661785325219),
 (534, 0.06622661785325219),
 (579, 0.06622661785325219),
 (1214, 0.06622661785325219),
 (1321, 0.06622661785325219),
 (1521, 0.06622661785325219),
 (1621, 0.06622661785325219),
 (2007, 0.06622661785325219),
 (2061, 0.06622661785325219),
 (2106, 0.06622661785325219),
 (2376, 0.06622661785325219),
 (2573, 0.06622661785325219),
 (2608, 0.06622661785325219),
 (2671, 0.06622661785325219),
 (3077, 0.06622661785325219),
 (3733, 0.06622661785325219),
 (3941, 0.06622661785325219),
 (4236, 0.06622661785325219),
 (4392, 0.06622661785325219),
 (4568, 0.06622661785325219),
 (4679, 0.06622661785325219),
 (331, 0.06554735253444621),
 (478, 0.06554735253444621),
 (491, 0.06554735253444621),
 (600, 0.06554735253444621),
 (963, 0.06554735253444621),
 (1958, 0.06554735253444621),
 (4399, 0.06554735253444621),
 (29, 0.064888568452305),
 (253, 0.064888568452305),
 (969, 0.064888568452305),
 (1175, 0.064888568452305),
 (1273, 0.064888568452305),
 (1405, 0.064888568452305),
 (6, 0.06424925662032355),
 (774, 0.06362847629757777),
 (850, 0.06362847629757777),
 (914, 0.06362847629757777),
 (1323, 0.06362847629757777),
 (1444, 0.06362847629757777),
 (1488, 0.06362847629757777),
 (1582, 0.06362847629757777),
 (1629, 0.06362847629757777),
 (1698, 0.06362847629757777),
 (1817, 0.06362847629757777),
 (1984, 0.06362847629757777),
 (2388, 0.06362847629757777),
 (2515, 0.06362847629757777),
 (2585, 0.06362847629757777),
 (2647, 0.06362847629757777),
 (2890, 0.06362847629757777),
 (2987, 0.06362847629757777),
 (3072, 0.06362847629757777),
 (3240, 0.06362847629757777),
 (3519, 0.06362847629757777),
 (3775, 0.06362847629757777),
 (3949, 0.06362847629757777),
 (4178, 0.06362847629757777),
 (4412, 0.06362847629757777),
 (4587, 0.06362847629757777),
 (4651, 0.06362847629757777),
 (4448, 0.06362847629757776),
 (610, 0.06335829046432676),
 (1598, 0.06302534916632545),
 (4798, 0.06302534916632545),
 (48, 0.06243905410544626),
 (1202, 0.06243905410544626),
 (1574, 0.06243905410544626),
 (3392, 0.06243905410544626),
 (3560, 0.06243905410544626),
 (4181, 0.06243905410544626),
 (4552, 0.06243905410544626),
 (353, 0.061868822488974594),
 (355, 0.061868822488974594),
 (1733, 0.061868822488974594),
 (2472, 0.061868822488974594),
 (3298, 0.061868822488974594),
 (189, 0.06131393394849658),
 (256, 0.06131393394849658),
 (584, 0.06131393394849658),
 (627, 0.06131393394849658),
 (838, 0.06131393394849658),
 (935, 0.06131393394849658),
 (1270, 0.06131393394849658),
 (1410, 0.06131393394849658),
 (1443, 0.06131393394849658),
 (1476, 0.06131393394849658),
 (1673, 0.06131393394849658),
 (1922, 0.06131393394849658),
 (1926, 0.06131393394849658),
 (1939, 0.06131393394849658),
 (2136, 0.06131393394849658),
 (2205, 0.06131393394849658),
 (2270, 0.06131393394849658),
 (2297, 0.06131393394849658),
 (2315, 0.06131393394849658),
 (2480, 0.06131393394849658),
 (2853, 0.06131393394849658),
 (3157, 0.06131393394849658),
 (3180, 0.06131393394849658),
 (3314, 0.06131393394849658),
 (3505, 0.06131393394849658),
 (3528, 0.06131393394849658),
 (3730, 0.06131393394849658),
 (3914, 0.06131393394849658),
 (3938, 0.06131393394849658),
 (3972, 0.06131393394849658),
 (3996, 0.06131393394849658),
 (4008, 0.06131393394849658),
 (4619, 0.06131393394849658),
 (2968, 0.06077371254627639),
 (3731, 0.06077371254627639),
 (38, 0.06024752331287778),
 (2603, 0.06024752331287778),
 (153, 0.05973476910894989),
 (640, 0.05973476910894989),
 (1751, 0.05973476910894989),
 (28, 0.059234887775909226),
 (218, 0.059234887775909226),
 (624, 0.059234887775909226),
 (653, 0.059234887775909226),
 (699, 0.059234887775909226),
 (739, 0.059234887775909226),
 (797, 0.059234887775909226),
 (945, 0.059234887775909226),
 (1005, 0.059234887775909226),
 (1360, 0.059234887775909226),
 (1413, 0.059234887775909226),
 (1579, 0.059234887775909226),
 (1850, 0.059234887775909226),
 (2271, 0.059234887775909226),
 (2274, 0.059234887775909226),
 (2394, 0.059234887775909226),
 (2621, 0.059234887775909226),
 (2715, 0.059234887775909226),
 (2725, 0.059234887775909226),
 (2877, 0.059234887775909226),
 (3081, 0.059234887775909226),
 (3155, 0.059234887775909226),
 (3441, 0.059234887775909226),
 (3753, 0.059234887775909226),
 (3781, 0.059234887775909226),
 (3989, 0.059234887775909226),
 (4072, 0.059234887775909226),
 (4169, 0.059234887775909226),
 (4477, 0.059234887775909226),
 (4557, 0.059234887775909226),
 (4564, 0.059234887775909226),
 (2226, 0.058747349544604664),
 (4627, 0.058747349544604664),
 (2474, 0.058271654674806495),
 (428, 0.057807331301607985),
 (206, 0.057353933467640436),
 (301, 0.057353933467640436),
 (547, 0.057353933467640436),
 (677, 0.057353933467640436),
 (693, 0.057353933467640436),
 (773, 0.057353933467640436),
 (941, 0.057353933467640436),
 (1156, 0.057353933467640436),
 (1573, 0.057353933467640436),
 (1655, 0.057353933467640436),
 (1727, 0.057353933467640436),
 (1789, 0.057353933467640436),
 (2161, 0.057353933467640436),
 (2762, 0.057353933467640436),
 (2812, 0.057353933467640436),
 (2872, 0.057353933467640436),
 (2925, 0.057353933467640436),
 (2970, 0.057353933467640436),
 (3098, 0.057353933467640436),
 (3126, 0.057353933467640436),
 (3217, 0.057353933467640436),
 (3356, 0.057353933467640436),
 (3483, 0.057353933467640436),
 (3571, 0.057353933467640436),
 (3777, 0.057353933467640436),
 (3891, 0.057353933467640436),
 (3976, 0.057353933467640436),
 (4216, 0.057353933467640436),
 (4332, 0.057353933467640436),
 (4655, 0.057353933467640436),
 (274, 0.05735393346764043),
 (2539, 0.05691103932244722),
 (4310, 0.05691103932244722),
 (230, 0.05647824947249049),
 (1282, 0.05647824947249049),
 (3947, 0.05647824947249049),
 (4506, 0.05647824947249049),
 (304, 0.05619514869490164),
 (44, 0.05564148840746572),
 (373, 0.05564148840746572),
 (526, 0.05564148840746572),
 (621, 0.05564148840746572),
 (1055, 0.05564148840746572),
 (1064, 0.05564148840746572),
 (1068, 0.05564148840746572),
 (1076, 0.05564148840746572),
 (1194, 0.05564148840746572),
 (1242, 0.05564148840746572),
 (1288, 0.05564148840746572),
 (1322, 0.05564148840746572),
 (1973, 0.05564148840746572),
 (2117, 0.05564148840746572),
 (2206, 0.05564148840746572),
 (2656, 0.05564148840746572),
 (2795, 0.05564148840746572),
 (2808, 0.05564148840746572),
 (2854, 0.05564148840746572),
 (2935, 0.05564148840746572),
 (3303, 0.05564148840746572),
 (3396, 0.05564148840746572),
 (3789, 0.05564148840746572),
 (3918, 0.05564148840746572),
 (4044, 0.05564148840746572),
 (4279, 0.05564148840746572),
 (4463, 0.05564148840746572),
 (4622, 0.05564148840746572),
 (4623, 0.05564148840746572),
 (4225, 0.05546053999849017),
 (1477, 0.05523681766661074),
 (3489, 0.05523681766661074),
 (1689, 0.05484084971070817),
 (1918, 0.05484084971070817),
 (2367, 0.05484084971070817),
 (3201, 0.05484084971070817),
 (59, 0.054453277011733005),
 (3520, 0.054453277011733005),
 (56, 0.05407380704358751),
 (61, 0.05407380704358751),
 (259, 0.05407380704358751),
 (263, 0.05407380704358751),
 (308, 0.05407380704358751),
 (408, 0.05407380704358751),
 (594, 0.05407380704358751),
 (613, 0.05407380704358751),
 (626, 0.05407380704358751),
 (991, 0.05407380704358751),
 (1231, 0.05407380704358751),
 (1328, 0.05407380704358751),
 (1373, 0.05407380704358751),
 (1506, 0.05407380704358751),
 (1520, 0.05407380704358751),
 (1544, 0.05407380704358751),
 (2433, 0.05407380704358751),
 (2479, 0.05407380704358751),
 (2600, 0.05407380704358751),
 (2683, 0.05407380704358751),
 (2783, 0.05407380704358751),
 (2787, 0.05407380704358751),
 (3060, 0.05407380704358751),
 (3420, 0.05407380704358751),
 (3481, 0.05407380704358751),
 (3488, 0.05407380704358751),
 (3513, 0.05407380704358751),
 (3627, 0.05407380704358751),
 (4139, 0.05407380704358751),
 (4198, 0.05407380704358751),
 (4403, 0.05407380704358751),
 (4704, 0.05407380704358751),
 (2832, 0.053702161354105465),
 (4711, 0.053702161354105465),
 (3061, 0.053338074706266496),
 (939, 0.05298129428260174),
 (4100, 0.05298129428260174),
 (122, 0.05263157894736841),
 (144, 0.05263157894736841),
 (356, 0.05263157894736841),
 (422, 0.05263157894736841),
 (487, 0.05263157894736841),
 (686, 0.05263157894736841),
 (737, 0.05263157894736841),
 (766, 0.05263157894736841),
 (878, 0.05263157894736841),
 (989, 0.05263157894736841),
 (1044, 0.05263157894736841),
 (1350, 0.05263157894736841),
 (1489, 0.05263157894736841),
 (1527, 0.05263157894736841),
 (1553, 0.05263157894736841),
 (1681, 0.05263157894736841),
 (1745, 0.05263157894736841),
 (1860, 0.05263157894736841),
 (1884, 0.05263157894736841),
 (1886, 0.05263157894736841),
 (1934, 0.05263157894736841),
 (1942, 0.05263157894736841),
 (2032, 0.05263157894736841),
 (2144, 0.05263157894736841),
 (2175, 0.05263157894736841),
 (2241, 0.05263157894736841),
 (2259, 0.05263157894736841),

In [223]:
sorted(list(enumerate(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(529, 0.23677853202210838),
 (4405, 0.22941573387056174),
 (3608, 0.22710998958306752),
 (3083, 0.1908854288927333),
 (2786, 0.18394180184548975)]

In [227]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]
  distances = similarity[movie_index]
  movie_list = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:6]

  for i in movie_list:
    print(new_df.iloc[i[0]].title)

In [228]:
recommend('Avatar')

Tears of the Sun
The Helix... Loaded
Apollo 18
Bucky Larson: Born to Be a Star
Attack the Block